### ISSUE TITLE
question regarding TEXT_Files

### ISSUE THREAD

**Issue by GregoryWu** [hclent/PyPatent#1]
Hi,
Is it possible to get data under TEXT_Files folder so that I may reduplicate the result?

Best,

Greg

**Comment by hclent** [comment]
Hi Greg!

Sorry for the extremely belated reply. I unfortunately missed the notification for this issue. I believe that I do still have the input files, and would be happy to send them along. Is there an e-mail you'd like me to send them to?

Cheers,
Heather

**Comment by GregoryWu** [comment]
Dear Heather,

Yes. Please send the input files to popegregory8219@gmail.com
Many thanks.

Best,

Greg

**Comment by hclent** [comment]
I have sent you a zip of the files  :)
